[project]
name = "20250827-django-cms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.7"
dependencies = [
    "django>=5.2.5",
    "httpx>=0.28.1",
]
