# Generated by Django 5.2.5 on 2025-08-27 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PublishedEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(max_length=150)),
                ('contents', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('original_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_version', to='cms.entry')),
            ],
            options={
                'verbose_name': 'Published Entry',
                'verbose_name_plural': 'Published Entries',
                'ordering': ['-published_at'],
            },
        ),
    ]
